import{a as S,S as q,i as p}from"./assets/vendor-Dnf_KHwu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="49079569-ff8624e89e8813a2e30953c9b",E="https://pixabay.com/api/";async function y(e,r=1){const s={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40};try{return(await S.get(E,{params:s})).data}catch(n){throw n}}const m=document.querySelector(".gallery");let P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function $(){m.innerHTML=""}function g(e){const r=e.map(({webformatURL:s,largeImageURL:n,tags:t,likes:o,views:c,comments:w,downloads:L})=>`
      <li class="photo-card">
        <a href="${n}">
          <img src="${s}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes: ${o}</b></p>
          <p class="info-item"><b>Views: ${c}</b></p>
          <p class="info-item"><b>Comments: ${w}</b></p>
          <p class="info-item"><b>Downloads: ${L}</b></p>
        </div>
      </li>
      `).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function b(){document.querySelector(".loader").hidden=!1}function f(){document.querySelector(".loader").hidden=!0}function l(e){p.error({title:"Error",message:e,position:"topRight"})}function h(e){p.info({title:"Info",message:e,position:"topRight"})}function I(){const e=document.querySelector(".gallery .photo-card");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}const O=document.querySelector(".search-form"),i=document.querySelector(".load-more");let u="",a=1,d=0;i.hidden=!0;O.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.currentTarget.query.value.trim(),u===""){l("Please enter a search query.");return}a=1,d=0,$(),i.hidden=!0,b();try{const r=await y(u,a);if(f(),!r.hits||r.hits.length===0){l("Sorry, there are no images matching your search query.");return}d=r.totalHits,g(r.hits),a*40<d&&(i.hidden=!1)}catch(r){f(),l("Something went wrong. Please try again later."),console.error(r)}});i.addEventListener("click",async()=>{a+=1,b();try{const e=await y(u,a);if(f(),!e.hits||e.hits.length===0){h("We're sorry, but you've reached the end of search results."),i.hidden=!0;return}g(e.hits),I(),a*40>=d&&(i.hidden=!0,h("We're sorry, but you've reached the end of search results."))}catch(e){f(),l("Something went wrong. Please try again later."),console.error(e)}});
//# sourceMappingURL=index.js.map
